# Generated by Django 2.1.7 on 2019-03-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mon',
            field=models.BooleanField(default=False, verbose_name='Montag'),
        ),
    ]
