# Generated by Django 2.1.7 on 2019-03-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_event_mon'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='event',
            name='fri',
            field=models.BooleanField(default=False, verbose_name='Freitag'),
        ),
        migrations.AddField(
            model_name='event',
            name='thu',
            field=models.BooleanField(default=False, verbose_name='Donnerstag'),
        ),
        migrations.AddField(
            model_name='event',
            name='tue',
            field=models.BooleanField(default=False, verbose_name='Dienstag'),
        ),
        migrations.AddField(
            model_name='event',
            name='wed',
            field=models.BooleanField(default=False, verbose_name='Mittwoch'),
        ),
    ]
