# Generated by Django 2.1.7 on 2019-03-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20190326_1345'),
        ('schedule', '0004_auto_20190326_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='teammember',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_teammember': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Contact', verbose_name='Teammitglied'),
        ),
        migrations.AlterField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
