# Generated by Django 2.1.7 on 2019-03-26 14:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20190326_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('mon', 'Montag'), ('tue', 'Dienstag'), ('wed', 'Mittwoch'), ('thu', 'Donnerstag'), ('fri', 'Freitag')], max_length=20),
        ),
    ]
