# Generated by Django 2.1.7 on 2019-03-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_event_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='fri',
        ),
        migrations.RemoveField(
            model_name='event',
            name='mon',
        ),
        migrations.RemoveField(
            model_name='event',
            name='thu',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tue',
        ),
        migrations.RemoveField(
            model_name='event',
            name='wed',
        ),
    ]
