# Generated by Django 2.1.7 on 2019-03-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20190326_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='exception',
            field=models.CharField(blank=True, max_length=200, verbose_name='Exception'),
        ),
        migrations.AddField(
            model_name='event',
            name='exception_day',
            field=models.DateField(null=True, verbose_name='Exception for Day'),
        ),
    ]
