# Generated by Django 2.1.7 on 2019-03-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20190326_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='exception_day',
        ),
        migrations.AddField(
            model_name='event',
            name='exception_until',
            field=models.DateField(null=True, verbose_name='Exception until'),
        ),
    ]
