# Generated by Django 2.1.7 on 2019-03-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20190326_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='active',
        ),
        migrations.AlterField(
            model_name='event',
            name='exception_until',
            field=models.DateField(blank=True, null=True, verbose_name='Exception until'),
        ),
    ]
