# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='people.Contact'),
            preserve_default=False,
        ),
    ]
