# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='contract_nr',
        ),
        migrations.AddField(
            model_name='contact',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notiz'),
        ),
        migrations.AddField(
            model_name='contact',
            name='on_address_list',
            field=models.BooleanField(default=True, verbose_name='In der Adressliste anzeigen'),
        ),
        migrations.AddField(
            model_name='contact',
            name='team_email_address',
            field=models.CharField(blank=True, max_length=128, verbose_name='Infinita-EMail'),
        ),
        migrations.AddField(
            model_name='student',
            name='after_school_care',
            field=models.BooleanField(default=False, verbose_name='in Nachmittagsbetreuung'),
        ),
        migrations.AddField(
            model_name='student',
            name='application_received',
            field=models.NullBooleanField(verbose_name='Bewerbung erhalten'),
        ),
        migrations.AddField(
            model_name='student',
            name='confirmation_status',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='(vorl.) Zusage'),
        ),
        migrations.AddField(
            model_name='student',
            name='district_school',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Einzugsschule'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_day',
            field=models.DateField(blank=True, null=True, verbose_name='Erster Tag an dieser Schule'),
        ),
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(blank=True, default='Deutsch', max_length=200, verbose_name='Sprache im Elternhaus'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_day',
            field=models.DateField(blank=True, null=True, verbose_name='Letzter Tag an dieser Schule'),
        ),
        migrations.AddField(
            model_name='student',
            name='obligatory_conference',
            field=models.NullBooleanField(verbose_name='Obl. EA'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_dialog',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Elterngespräch'),
        ),
        migrations.AddField(
            model_name='student',
            name='planned_enrollment_age',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Einschulungsalter'),
        ),
        migrations.AddField(
            model_name='student',
            name='planned_enrollment_year',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Einschulungsjahr'),
        ),
        migrations.AddField(
            model_name='student',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Anmerkung'),
        ),
        migrations.AddField(
            model_name='student',
            name='sitting',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Hospitation'),
        ),
        migrations.AddField(
            model_name='student',
            name='waitlist_position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Position Warteliste'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Aktiv'), ('in_admission_procedure', 'Bewerbungsverfahren'), ('waitlisted', 'Warteliste'), ('intent_declared', 'Absichtserklärung'), ('cancelled', 'abgesagt/abgelaufen'), ('alumnus', 'Ehemalig'), ('special', 'Ausnahme')], max_length=32, null=True, verbose_name='Status'),
        ),
    ]
