# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_address_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='', max_length=200, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='kind',
            field=models.CharField(choices=[('oth', 'Other'), ('prs', 'Person'), ('com', 'Company'), ('org', 'Organization')], max_length=3, verbose_name='Kind'),
        ),
    ]
