# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20161125_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='First Name'),
        ),
    ]
