# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20161125_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='family',
        ),
        migrations.AddField(
            model_name='student',
            name='guardians',
            field=models.ManyToManyField(to='people.Contact'),
        ),
    ]
