# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20161125_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Address'),
        ),
    ]
