# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaddress',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_address',
            field=models.CharField(blank=True, max_length=128, verbose_name='EMail Address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Phone Number'),
        ),
        migrations.DeleteModel(
            name='EMailAddress',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
