# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20161125_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name', 'first_name'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.CharField(blank=True, max_length=128, verbose_name='EMail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Phone'),
        ),
    ]
