# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20161125_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name', 'first_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='student',
            name='contract_nr',
            field=models.IntegerField(null=True, verbose_name='Contract #'),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='student',
            name='entry_nr',
            field=models.IntegerField(default=-1, verbose_name='Entry #'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('__', 'other/unspecified')], max_length=2, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_sibling',
            field=models.NullBooleanField(verbose_name='Sibling'),
        ),
        migrations.AddField(
            model_name='student',
            name='pob',
            field=models.CharField(max_length=200, null=True, verbose_name='Place of Birth'),
        ),
        migrations.AddField(
            model_name='student',
            name='privacy_policy_agreement',
            field=models.NullBooleanField(verbose_name='Privacy Policy Agreement'),
        ),
        migrations.AddField(
            model_name='student',
            name='vaccination_policy_agreement',
            field=models.NullBooleanField(verbose_name='Vaccination Policy Agreement'),
        ),
    ]
