# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20161125_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='citizenship',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Citizenship'),
        ),
        migrations.AddField(
            model_name='student',
            name='denomination',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Religious Denomination'),
        ),
        migrations.AddField(
            model_name='student',
            name='level_ofs',
            field=models.IntegerField(null=True, verbose_name='Class Level (at Reference)'),
        ),
        migrations.AddField(
            model_name='student',
            name='level_ref',
            field=models.IntegerField(null=True, verbose_name='Class Level Reference'),
        ),
        migrations.AlterField(
            model_name='student',
            name='contract_nr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contract #'),
        ),
        migrations.AlterField(
            model_name='student',
            name='entry_nr',
            field=models.IntegerField(blank=True, verbose_name='Entry #'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female'), ('__', 'other/unspecified')], max_length=2, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardians',
            field=models.ManyToManyField(blank=True, to='people.Contact'),
        ),
    ]
