# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20161125_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_enrollment',
            field=models.IntegerField(blank=True, null=True, verbose_name='First Enrollment (at any School)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_ofs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Class Level (at Reference)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_ref',
            field=models.IntegerField(blank=True, null=True, verbose_name='Class Level Reference'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pob',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Place of Birth'),
        ),
    ]
