# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20161129_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Postadresse', 'verbose_name_plural': 'Postadressen'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name', 'first_name'], 'verbose_name': 'Kontakt', 'verbose_name_plural': 'Kontakte'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name', 'first_name'], 'verbose_name': 'SchülerIn', 'verbose_name_plural': 'SchülerInnen'},
        ),
        migrations.AlterField(
            model_name='address',
            name='alternative',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Alternativ'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=200, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=200, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Mobil'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='kind',
            field=models.CharField(choices=[('oth', 'Andere'), ('prs', 'Person'), ('com', 'Firma'), ('org', 'Organisation/Amt/etc')], max_length=3, verbose_name='Art'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Festnetz'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='citizenship',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Staatsbürgerschaft'),
        ),
        migrations.AlterField(
            model_name='student',
            name='contract_nr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Schulvertrag #'),
        ),
        migrations.AlterField(
            model_name='student',
            name='denomination',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Religionszugehörigkeit'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='student',
            name='entry_nr',
            field=models.IntegerField(blank=True, verbose_name='Eingangsnummer'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_enrollment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Erste Einschulung'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'männlich'), ('f', 'weiblich'), ('__', 'anderes/ohne Angabe')], max_length=2, null=True, verbose_name='Geschlecht'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardians',
            field=models.ManyToManyField(blank=True, related_name='students', to='people.Contact', verbose_name='Erziehungsberechtigte'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_sibling',
            field=models.NullBooleanField(verbose_name='Geschwisterkind'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_ofs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Klassenstufe (bei Referenz)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_ref',
            field=models.IntegerField(blank=True, null=True, verbose_name='Klassenstufen-Referenz'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pob',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Geburtsort'),
        ),
        migrations.AlterField(
            model_name='student',
            name='privacy_policy_agreement',
            field=models.NullBooleanField(verbose_name='Datenschutzerklärung'),
        ),
        migrations.AlterField(
            model_name='student',
            name='vaccination_policy_agreement',
            field=models.NullBooleanField(verbose_name='Infektionsschutzgesetz'),
        ),
    ]
