# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_auto_20161129_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Address', verbose_name='Postadresse'),
        ),
    ]
