# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-05 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_auto_20161129_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active Student'), ('alumnus', 'Alumnus'), ('waitlisted', 'waitlisted'), ('intent_declared', 'Declaration of Intent'), ('rejected', 'rejected'), ('applied', 'Application received'), ('admission_dialog', 'in Admission Dialog'), ('sitting', 'sitting in')], max_length=20, null=True, verbose_name='Status'),
        ),
    ]
