# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-05 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Aktuell SchülerIn dieser Schule'), ('alumnus', 'EhemaligeR'), ('waitlisted', 'auf der Warteliste'), ('intent_declared', 'Absichtserklärung'), ('rejected', 'abgesagt'), ('applied', 'im Bewerbungsverfahren'), ('admission_dialog', 'Aufnahmegespräch'), ('sitting', 'Hospitation')], max_length=20, null=True, verbose_name='Status'),
        ),
    ]
