# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-18 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0025_student_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='entry_nr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Eingangsnummer'),
        ),
    ]
